name: CI

on:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Protect dev branch
        uses: peter-evans/protect-branch@v3.0.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: "dev"
          enforce_admins: true
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
          require_approving_reviews: true
          include_admins: true

      - name: Protect gh-pages branch
        uses: peter-evans/protect-branch@v3.0.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: "gh-pages"
          enforce_admins: true
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
          require_approving_reviews: true
          include_admins: true

      - name: Build and Deploy Preview
        env:
          NODE_ENV: production
        run: |
          yarn build
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -B gh-pages
          git add -f build/
          git commit -m "Deploy preview"
          git push -f origin gh-pages
